app = "gatcor-backend"
primary_region = "sin" # Singapore region

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[http_service.ports]]
  port = 80
  handlers = ["http"]
  force_https = true

[[http_service.ports]]
  port = 443
  handlers = ["tls", "http"] 